# words.py

# List of words for the game
word_list = [
    'wares', 'soup', 'mount', 'extend', 'brown', 'expert', 'tired', 'humidity',
    'backpack', 'crust', 'dent', 'market', 'knock', 'smite', 'windy', 'coin',
    'throw', 'silence', 'bluff', 'downfall', 'climb', 'lying', 'weaver', 'snob',
    'kickoff', 'match', 'quaker', 'foreman', 'excite', 'thinking', 'mend',
    'allergen', 'pruning', 'coat', 'emerald', 'coherent', 'manic', 'multiple',
    'square', 'funded', 'funnel', 'sailing', 'dream', 'mutation', 'strict',
    'mystic', 'film', 'guide', 'strain', 'bishop', 'settle', 'plateau',
    'emigrate', 'marching', 'optimal', 'medley', 'endanger', 'wick', 'condone',
    'schema', 'rage', 'figure', 'plague', 'aloof', 'there', 'reusable',
    'refinery', 'suffer', 'affirm', 'captive', 'flipping', 'prolong', 'main',
    'coral', 'dinner', 'rabbit', 'chill', 'seed', 'born', 'shampoo', 'italian',
    'giggle', 'roost', 'palm', 'globe', 'wise', 'grandson', 'running', 'sunlight',
    'spending', 'crunch', 'tangle', 'forego', 'tailor', 'divinity', 'probe',
    'bearded', 'premium', 'featured', 'serve', 'borrower', 'examine', 'legal',
    'outlive', 'unnamed', 'unending', 'snow', 'whisper', 'bundle', 'bracket',
    'deny', 'blurred', 'pentagon', 'reformed', 'polarity', 'jumping', 'gain',
    'laundry', 'hobble', 'culture', 'whittle', 'docket', 'mayhem', 'build',
    'peel', 'board', 'keen', 'glorious', 'singular', 'cavalry', 'present',
    'cold', 'hook', 'salted', 'just', 'dumpling', 'glimmer', 'drowning',
    'admiral', 'sketch', 'subject', 'upright', 'sunshine', 'slide', 'calamity',
    'gurney', 'adult', 'adore', 'weld', 'masking', 'print', 'wishful', 'foyer',
    'tofu', 'machete', 'diced', 'behemoth', 'rout', 'midwife', 'neglect', 'mass',
    'game', 'stocking', 'folly', 'action', 'bubbling', 'scented', 'sprinter',
    'bingo', 'egyptian', 'comedy', 'rung', 'outdated', 'radical', 'escalate',
    'mutter', 'desert', 'memento', 'kayak', 'talon', 'portion', 'affirm',
    'dashing', 'fare', 'battle', 'pupil', 'rite', 'smash', 'true', 'entrance',
    'counting', 'peruse', 'dioxide', 'hermit', 'carving', 'backyard', 'homeless',
    'packet', 'tickle', 'coming', 'leave', 'swing', 'thicket', 'reserve',
    'murder', 'costly', 'corduroy', 'bump', 'oncology', 'swatch', 'rundown',
    'steal', 'teller', 'cable', 'oily', 'official', 'abyss', 'schism', 'failing',
    'guru', 'trim', 'alfalfa', 'doubt', 'booming', 'bruised', 'playful',
    'kicker', 'jockey', 'handmade', 'landfall', 'rhythm', 'keep', 'reassure',
    'garland', 'sauna', 'idiom', 'fluent', 'lope', 'gland', 'amend', 'fashion',
    'treaty', 'standing', 'current', 'sharpen', 'cinder', 'idealist', 'festive',
    'frame', 'molten', 'sill', 'glisten', 'fearful', 'basement', 'minutia',
    'stick', 'soot', 'static', 'crazed', 'upset', 'robotics', 'dwarf', 'shield',
    'butler', 'stitch', 'stub', 'sabotage', 'parlor', 'prompt', 'heady', 'horn',
    'bygone', 'rework', 'painful', 'composer', 'glance', 'acquit', 'eagle',
    'solvent', 'backbone', 'smart', 'atlas', 'leap', 'danger', 'bruise',
    'seminar', 'tinge', 'trip', 'narrow', 'while', 'jaguar', 'seminary',
    'command', 'cassette', 'draw', 'anchovy', 'scream', 'blush', 'organic',
    'applause', 'parallel', 'trolley', 'pathos', 'origin', 'hang', 'pungent',
    'angular', 'stubble', 'painted', 'forward', 'saddle', 'muddy', 'orchid',
    'prudence', 'disprove', 'yiddish', 'lobbying', 'neuron', 'tumor', 'haitian',
    'swift', 'mantel', 'wardrobe', 'consist', 'storied', 'extreme', 'payback',
    'control', 'dummy', 'influx', 'realtor', 'detach', 'flake', 'consign',
    'adjunct', 'stylized', 'weep', 'prepare', 'pioneer', 'tail', 'platoon',
    'exercise', 'clap', 'actor', 'spark', 'dope', 'phrase', 'welsh', 'wall',
    'whine', 'fickle', 'wrong', 'stamina', 'dazed', 'cramp', 'filet', 'foresee',
    'seller', 'award', 'mare', 'uncover', 'ease', 'buttery', 'luxury', 'bigotry',
    'photon', 'snow', 'oppress', 'blessed', 'call', 'stain', 'amber', 'rental',
    'nominee', 'township', 'adhesive', 'lengthy', 'swarm', 'court', 'baguette',
    'leper', 'vital', 'push', 'digger', 'setback', 'accused', 'taker', 'genie',
    'reverse', 'fake', 'widowed', 'renewed', 'goodness', 'curse', 'shocked',
    'shove', 'marked', 'interact', 'mane', 'hawk', 'kidnap', 'noble', 'proton',
    'effort', 'patriot', 'showcase', 'parish', 'mosaic', 'coil', 'aide',
    'breeder', 'concoct', 'pathway', 'hearing', 'bayou', 'regimen', 'drain',
    'bereft', 'matte', 'bill', 'medal', 'prickly', 'sarcasm', 'stuffy', 'allege',
    'monopoly', 'lighter', 'repair', 'worship', 'vent', 'hybrid', 'buffet',
    'lively'
]

# Dictionary to store hints for each word
word_hints = {
    'wares': 'Items for sale.',
    'soup': 'A liquid food, often served warm.',
    'mount': 'To climb or ascend.',
    'extend': 'To make something longer.',
    'brown': 'A color often associated with earth.',
    'expert': 'A person with extensive knowledge or skill.',
    'tired': 'Feeling in need of rest or sleep.',
    'humidity': 'The amount of water vapor in the air.',
    'backpack': 'A bag carried on the back, often used for hiking.',
    'crust': 'The outer layer of bread or the Earth.',
    'dent': 'A small hollow in a surface made by pressure or a blow.',
    'market': 'A place where goods are bought and sold.',
    'knock': 'To strike a surface noisily to attract attention.',
    'smite': 'To strike with a firm blow.',
    'windy': 'Having a lot of wind.',
    'coin': 'A flat, typically round piece of metal used as money.',
    'throw': 'To propel something through the air.',
    'silence': 'The complete absence of sound.',
    'bluff': 'To deceive someone about one\'s abilities or intentions.',
    'downfall': 'A loss of power, prosperity, or status.',
    'climb': 'To go or come up a slope, incline, or staircase.',
    'lying': 'Present participle of lie, meaning to recline or to tell a falsehood.',
    'weaver': 'A person who weaves fabric.',
    'snob': 'A person who believes themselves superior to others.',
    'kickoff': 'The start of an event or activity.',
    'match': 'A contest in which people or teams compete against each other.',
    'quaker': 'A member of the Religious Society of Friends.',
    'foreman': 'A worker who supervises and directs other workers.',
    'excite': 'To cause strong feelings of enthusiasm and eagerness.',
    'thinking': 'The process of considering or reasoning about something.',
    'mend': 'To repair something that is broken or damaged.',
    'allergen': 'A substance that causes an allergic reaction.',
    'pruning': 'The process of trimming a plant by cutting away dead or overgrown branches.',
    'coat': 'An outer garment worn outdoors.',
    'emerald': 'A bright green precious stone.',
    'coherent': 'Logical and consistent.',
    'manic': 'Showing wild and apparently deranged excitement and energy.',
    'multiple': 'Having or involving several parts, elements, or members.',
    'square': 'A shape with four equal sides and four right angles.',
    'funded': 'Provided with money for a particular purpose.',
    'funnel': 'A tube or pipe that is wide at the top and narrow at the bottom.',
    'sailing': 'The action of sailing in a ship or boat.',
    'dream': 'A series of thoughts, images, and sensations occurring in a person\'s mind during sleep.',
    'mutation': 'The changing of the structure of a gene.',
    'strict': 'Demanding that rules concerning behavior are obeyed and observed.',
    'mystic': 'A person who seeks by contemplation and self-surrender to obtain unity with the absolute.',
    'film': 'A thin flexible strip of plastic or other material coated with light-sensitive emulsion.',
    'guide': 'A person who advises or shows the way to others.',
    'strain': 'A force tending to pull or stretch something.',
    'bishop': 'A senior member of the Christian clergy.',
    'settle': 'To resolve or reach an agreement about an argument or problem.',
    'plateau': 'An area of relatively level high ground.',
    'emigrate': 'To leave one\'s own country in order to settle permanently in another.',
    'marching': 'Walking in a military manner with a regular measured tread.',
    'optimal': 'Best or most favorable.',
    'medley': 'A varied mixture of people or things.',
    'endanger': 'To put someone or something at risk or in danger.',
    'wick': 'A strip of porous material up which liquid fuel is drawn by capillary action to the flame.',
    'condone': 'To accept and allow behavior that is considered morally wrong or offensive to continue.',
    'schema': 'A representation of a plan or theory in the form of an outline or model.',
    'rage': 'Violent uncontrollable anger.',
    'figure': 'A number, especially one which forms part of official statistics.',
    'plague': 'A contagious bacterial disease characterized by fever and delirium.',
    'aloof': 'Not friendly or forthcoming; cool and distant.',
    'there': 'In, at, or to that place or position.',
    'reusable': 'Able to be used again or more than once.',
    'refinery': 'An industrial installation where a substance is refined.',
    'suffer': 'To experience or be subjected to something bad or unpleasant.',
    'affirm': 'To state emphatically or publicly.',
    'captive': 'A person who has been taken prisoner or an animal that has been confined.',
    'flipping': 'Turning over or causing to turn over with a sudden quick movement.',
    'prolong': 'To extend the duration of.',
    'main': 'Chief in size or importance.',
    'coral': 'A hard stony substance secreted by certain marine coelenterates.',
    'dinner': 'The main meal of the day, taken either around midday or in the evening.',
    'rabbit': 'A small burrowing mammal with long ears and soft fur.',
    'chill': 'A feeling of coldness, often accompanied by shivering.',
    'seed': 'The unit of reproduction of a flowering plant.',
    'born': 'Existing as a result of birth.',
    'shampoo': 'A liquid preparation for washing the hair.',
    'italian': 'Relating to Italy, its people, or their language.',
    'giggle': 'To laugh lightly in a nervous or silly way.',
    'roost': 'A place where birds regularly settle or congregate to rest.',
    'palm': 'The inner surface of the hand between the wrist and fingers.',
    'globe': 'The earth.',
    'wise': 'Having or showing experience, knowledge, and good judgment.',
    'grandson': 'A son of one\'s son or daughter.',
    'running': 'The action or movement of a runner.',
    'sunlight': 'Light from the sun.',
    'spending': 'The act of paying out money.',
    'crunch': 'A loud muffled grinding sound.',
    'tangle': 'A confused mass of something twisted together.',
    'forego': 'To precede in place or time.',
    'tailor': 'A person whose occupation is making fitted clothes.',
    'divinity': 'The state or quality of being divine.',
    'probe': 'A thorough investigation into a crime or other matter.',
    'bearded': 'Having a growth of hair on the cheeks and chin.',
    'premium': 'An amount to be paid for an insurance policy.',
    'featured': 'Having distinctive attributes or aspects of a special kind.',
    'serve': 'To perform duties or services for another person or an organization.',
    'borrower': 'A person or organization that takes and uses something belonging to someone else.',
    'examine': 'To inspect someone or something in detail.',
    'legal': 'Relating to the law.',
    'outlive': 'To live longer than.',
    'unnamed': 'Not having a name.',
    'unending': 'Having or seeming to have no end.',
    'snow': 'Atmospheric water vapor frozen into ice crystals.',
    'whisper': 'To speak very softly using one\'s breath.',
    'bundle': 'A collection of things or quantity of material tied or wrapped up together.',
    'bracket': 'A category of people or things that are similar or fall between specified limits.',
    'deny': 'To refuse to accept or acknowledge.',
    'blurred': 'Unable to see or be seen clearly.',
    'pentagon': 'A five-sided polygon.',
    'reformed': 'Having been changed or improved.',
    'polarity': 'The property of having poles or being polar.',
    'jumping': 'The action of jumping.',
    'gain': 'To obtain or secure something desired or favorable.',
    'laundry': 'Clothes and linens that need to be washed or that have been newly washed.',
    'hobble': 'To walk in an awkward way, typically because of pain.',
    'culture': 'The arts and other manifestations of human intellectual achievement.',
    'whittle': 'To carve wood into an object by repeatedly cutting small slices from it.',
    'docket': 'A calendar or list of cases for trial or people having cases pending.',
    'mayhem': 'Violent or extreme disorder.',
    'build': 'To construct something by putting parts or material together.',
    'peel': 'To remove the outer covering or skin from a fruit or vegetable.',
    'board': 'A long, thin, flat piece of wood or other hard material.',
    'keen': 'Having or showing eagerness or enthusiasm.',
    'glorious': 'Having, worthy of, or bringing fame or admiration.',
    'singular': 'Exceptionally good or great; remarkable.',
    'cavalry': 'Soldiers who fought on horseback.',
    'present': 'Existing or occurring now.',
    'cold': 'Of or at a low or relatively low temperature.',
    'hook': 'A piece of metal or other hard material curved or bent back at an angle.',
    'salted': 'Having had salt added.',
    'just': 'Based on or behaving according to what is morally right and fair.',
    'dumpling': 'A small savory ball of dough boiled in water or in a stew.',
    'glimmer': 'A faint or wavering light.',
    'drowning': 'The process of dying through submersion in and inhalation of water.',
    'admiral': 'A high-ranking officer in the navy.',
    'sketch': 'A rough or unfinished drawing or painting.',
    'subject': 'A person or thing that is being discussed, described, or dealt with.',
    'upright': 'Vertical; erect.',
    'sunshine': 'Direct sunlight unbroken by cloud.',
    'slide': 'To move smoothly along a surface while maintaining continuous contact with it.',
    'calamity': 'An event causing great and often sudden damage or distress.',
    'gurney': 'A wheeled stretcher used for transporting hospital patients.',
    'adult': 'A person who is fully grown or developed.',
    'adore': 'To love and respect someone deeply.',
    'weld': 'To join together metal parts by heating the surfaces to the point of melting.',
    'masking': 'The process of covering or concealing something.',
    'print': 'To produce books, newspapers, etc., by applying inked types to paper.',
    'wishful': 'Having or expressing a desire or hope for something to happen.',
    'foyer': 'An entrance hall or other open area in a building used by the public.',
    'tofu': 'A soft, bland, white cheese-like food made from soybeans.',
    'machete': 'A broad, heavy knife used as an implement or weapon.',
    'diced': 'Cut into small cubes.',
    'behemoth': 'A huge or monstrous creature.',
    'rout': 'A disorderly retreat of defeated troops.',
    'midwife': 'A person trained to assist women in childbirth.',
    'neglect': 'To fail to care for properly.',
    'mass': 'A large body of matter with no definite shape.',
    'game': 'A form of play or sport, especially a competitive one played according to rules.',
    'stocking': 'A close-fitting, elastic garment covering the foot and lower part of the leg.',
    'folly': 'Lack of good sense; foolishness.',
    'action': 'The fact or process of doing something, typically to achieve an aim.',
    'bubbling': 'Containing bubbles or making a bubbling sound.',
    'scented': 'Having a pleasant, distinctive smell.',
    'sprinter': 'A person who runs at top speed, especially over a short distance.',
    'bingo': 'A game in which players mark off numbers on cards as the numbers are drawn.',
    'egyptian': 'Relating to Egypt or its people.',
    'comedy': 'Professional entertainment consisting of jokes and satirical sketches.',
    'rung': 'A horizontal support on a ladder for a person\'s foot.',
    'outdated': 'No longer in use or fashionable; obsolete.',
    'radical': 'Relating to or affecting the fundamental nature of something.',
    'escalate': 'To increase rapidly.',
    'mutter': 'To say something in a low or barely audible voice.',
    'desert': 'A waterless, desolate area of land with little or no vegetation.',
    'memento': 'An object kept as a reminder of a person or event.',
    'kayak': 'A canoe of a type used originally by the Inuit.',
    'talon': 'A claw, especially one belonging to a bird of prey.',
    'portion': 'A part of a whole.',
    'affirm': 'To state emphatically or publicly.',
    'dashing': 'Energetic, spirited, and stylish.',
    'fare': 'The money a passenger on public transportation has to pay.',
    'battle': 'A sustained fight between large organized armed forces.',
    'pupil': 'A student in school.',
    'rite': 'A religious or other solemn ceremony or act.',
    'smash': 'To break something violently into pieces.',
    'true': 'In accordance with fact or reality.',
    'entrance': 'An opening, such as a door, passage, or gate, that allows access to a place.',
    'counting': 'The action of finding the number of elements of a finite set of objects.',
    'peruse': 'To read something, typically in a thorough or careful way.',
    'dioxide': 'An oxide containing two atoms of oxygen in its molecule.',
    'hermit': 'A person living in solitude as a religious discipline.',
    'carving': 'The action of cutting a hard material in order to produce an object or design.',
    'backyard': 'A yard at the back of a house.',
    'homeless': 'Without a home, and therefore typically living on the streets.',
    'medley': 'A varied mixture of people or things.',
    'packet': 'A small container or envelope.',
    'tickle': 'To touch or stroke lightly so as to cause laughter or twitching movements.',
    'coming': 'Approaching; forthcoming.',
    'leave': 'To go away from.',
    'swing': 'To move or cause to move back and forth or from side to side while suspended.',
    'thicket': 'A dense group of bushes or trees.',
    'reserve': 'To keep back or set aside, especially for future use or contingency.',
    'murder': 'The unlawful premeditated killing of one human being by another.',
    'costly': 'Costing a lot; expensive.',
    'corduroy': 'A thick cotton fabric with velvety ribs.',
    'bump': 'A light blow or a jolting collision.',
    'oncology': 'The study and treatment of tumors.',
    'swatch': 'A small sample of fabric intended to demonstrate the look of a larger piece.',
    'rundown': 'A reduction in the productivity or activities of a company or institution.',
    'steal': 'To take another person\'s property without permission or legal right.',
    'teller': 'A person employed to deal with customers\' transactions in a bank.',
    'cable': 'A thick rope of wire or nonmetallic fiber, typically used for construction.',
    'oily': 'Containing or covered with oil.',
    'official': 'Relating to an authority or public body and its activities and responsibilities.',
    'abyss': 'A deep or seemingly bottomless chasm.',
    'schism': 'A split or division between strongly opposed sections or parties.',
    'failing': 'A weakness, especially in character; a shortcoming.',
    'guru': 'A Hindu spiritual teacher.',
    'trim': 'To make something neat or of the required size or form by cutting away irregular parts.',
    'alfalfa': 'A plant with clover-like leaves and bluish flowers, used as fodder.',
    'doubt': 'A feeling of uncertainty or lack of conviction.',
    'booming': 'Having a period of great prosperity or rapid economic growth.',
    'bruised': 'Injured by a blow or impact to the body.',
    'playful': 'Fond of games and amusement; lighthearted.',
    'kicker': 'A player in football who kicks the ball.',
    'jockey': 'A person who rides in horse races, especially as a profession.',
    'handmade': 'Made by hand, not by machine, and typically therefore of superior quality.',
    'landfall': 'The arrival at land of a ship, aircraft, or traveler.',
    'rhythm': 'A strong, regular, repeated pattern of movement or sound.',
    'keep': 'To have or retain possession of.',
    'reassure': 'To say or do something to remove the doubts and fears of someone.',
    'garland': 'A wreath of flowers and leaves, worn on the head or hung as a decoration.',
    'sauna': 'A small room used as a hot-air or steam bath for cleaning and refreshing the body.',
    'idiom': 'A group of words established by usage as having a meaning not deducible from those of the individual words.',
    'fluent': 'Able to express oneself easily and articulately.',
    'lope': 'To run or move with a long bounding stride.',
    'gland': 'An organ in the human or animal body that secretes particular chemical substances.',
    'amend': 'To make minor changes in order to make it fairer or more accurate.',
    'fashion': 'A popular or the latest style of clothing, hair, decoration, or behavior.',
    'treaty': 'A formally concluded and ratified agreement between countries.',
    'standing': 'The position, status, or reputation of someone or something.',
    'current': 'Belonging to the present time; happening or being used or done now.',
    'sharpen': 'To make or become sharp or sharper.',
    'cinder': 'A small piece of partly burned coal or wood that has stopped giving off flames.',
    'idealist': 'A person who is guided more by ideals than by practical considerations.',
    'festive': 'Relating to a festival, especially Christmas.',
    'frame': 'A rigid structure that surrounds or encloses something.',
    'molten': 'Liquefied by heat.',
    'sill': 'A shelf or slab of stone, wood, or metal at the foot of a window.',
    'glisten': 'To shine with a sparkling light.',
    'fearful': 'Feeling afraid; showing fear or anxiety.',
    'basement': 'The floor of a building partly or entirely below ground level.',
    'minutia': 'The small, precise, or trivial details of something.',
    'stick': 'A thin piece of wood that has fallen or been cut from a tree.',
    'soot': 'A black powdery or flaky substance consisting largely of amorphous carbon.',
    'static': 'Lacking in movement, action, or change.',
    'crazed': 'Mad; insane.',
    'upset': 'To make someone unhappy, disappointed, or worried.',
    'robotics': 'The branch of technology that deals with the design, construction, operation.',
    'dwarf': 'A person who is unusually small.',
    'shield': 'A broad piece of metal or another suitable material, held by straps or a handle.',
    'butler': 'The chief male servant of a household.',
    'stitch': 'A loop of thread or yarn resulting from a single pass of the needle in sewing.',
    'stub': 'The truncated remnant of a pencil, cigarette, or similar-shaped object.',
    'sabotage': 'To deliberately destroy, damage, or obstruct something.',
    'parlor': 'A sitting room in a private house.',
    'prompt': 'To cause or bring about an action or feeling.',
    'heady': 'Having a strong or exhilarating effect.',
    'horn': 'A hard permanent outgrowth, often curved and pointed, found in pairs on the heads.',
    'bygone': 'Belonging to an earlier time.',
    'rework': 'To make changes to the original version of something.',
    'painful': 'Causing physical pain.',
    'composer': 'A person who writes music, especially as a professional occupation.',
    'glance': 'To take a brief or hurried look.',
    'acquit': 'To free someone from a criminal charge by a verdict of not guilty.',
    'eagle': 'A large bird of prey with a massive hooked bill and long broad wings.',
    'solvent': 'Able to pay all debts.',
    'backbone': 'The series of vertebrae extending from the skull to the pelvis.',
    'smart': 'Having or showing a quick-witted intelligence.',
    'atlas': 'A book of maps or charts.',
    'leap': 'To jump or spring a long way, to a great height, or with great force.',
    'danger': 'The possibility of suffering harm or injury.',
    'bruise': 'An injury appearing as an area of discolored skin on the body.',
    'seminar': 'A conference or other meeting for discussion or training.',
    'tinge': 'A trace of a color.',
    'trip': 'A journey or excursion, especially for pleasure.',
    'narrow': 'Of small width in relation to length.',
    'while': 'A period of time.',
    'jaguar': 'A large cat native to the Americas.',
    'seminary': 'A college that prepares students to be priests, ministers, or rabbis.',
    'command': 'To give an authoritative order.',
    'cassette': 'A sealed plastic unit containing a length of audiotape, videotape.',
    'draw': 'To produce a picture or diagram by making lines and marks.',
    'anchovy': 'A small, common saltwater fish of the herring family.',
    'scream': 'To make a loud, piercing cry.',
    'blush': 'To become red in the face from shyness, embarrassment, or shame.',
    'organic': 'Relating to or derived from living matter.',
    'applause': 'The clapping of hands to show approval or appreciation.',
    'parallel': 'Side by side and having the same distance continuously between them.',
    'trolley': 'A wheeled vehicle running on tracks, used for transporting goods.',
    'pathos': 'A quality that evokes pity or sadness.',
    'origin': 'The point or place where something begins, arises, or is derived.',
    'hang': 'To suspend or be suspended from above with the lower part dangling free.',
    'pungent': 'Having a sharply strong taste or smell.',
    'angular': 'Having angles or sharp corners.',
    'stubble': 'The short, stiff stalks of grain or hay remaining after harvesting.',
    'painted': 'Covered or decorated with paint.',
    'forward': 'Directed or moving ahead.',
    'saddle': 'A seat fastened on the back of a horse or other animal for riding.',
    'muddy': 'Covered in or full of mud.',
    'orchid': 'A plant with complex flowers that are often showy or bizarrely shaped.',
    'prudence': 'The quality of being prudent; cautiousness.',
    'disprove': 'To prove that something is false.',
    'yiddish': 'A language used by Jewish people in central and eastern Europe.',
    'lobbying': 'The activity of trying to persuade someone in authority.',
    'neuron': 'A specialized cell transmitting nerve impulses.',
    'tumor': 'A swelling of a part of the body, generally without inflammation.',
    'haitian': 'Relating to Haiti or its people.',
    'swift': 'Happening quickly or promptly.',
    'mantel': 'A beam, stone, or arch serving as a lintel to support the masonry above a fireplace.',
    'wardrobe': 'A large, tall cupboard in which clothes may be hung or stored.',
    'consist': 'To be composed or made up of.',
    'storied': 'Celebrated or famous in history or story.',
    'extreme': 'Reaching a high or the highest degree; very great.',
    'payback': 'The return of an injury or bad deed in kind.',
    'control': 'The power to influence or direct people\'s behavior or the course of events.',
    'dummy': 'A model or replica of a human being.',
    'influx': 'An arrival or entry of large numbers of people or things.',
    'realtor': 'A person who acts as an agent for the sale and purchase of buildings and land.',
    'detach': 'To disengage something and remove it.',
    'flake': 'A small, flat, thin piece of something, typically one that has broken away.',
    'consign': 'To deliver something to a person\'s keeping.',
    'adjunct': 'A thing added to something else as a supplementary rather than an essential part.',
    'stylized': 'Depicted or treated in a mannered and nonrealistic style.',
    'weep': 'To shed tears.',
    'prepare': 'To make something ready for use or consideration.',
    'pioneer': 'A person who is among the first to explore or settle a new country or area.',
    'tail': 'The rear end of an animal, especially when prolonged beyond the rest of the body.',
    'platoon': 'A subdivision of a company of soldiers, usually forming a tactical unit.',
    'exercise': 'Activity requiring physical effort, carried out to sustain or improve health.',
    'dummy': 'A model or replica of a human being.',
    'clap': 'To strike the palms of the hands together repeatedly, typically to applaud.',
    'actor': 'A person whose profession is acting on the stage, in movies, or on television.',
    'spark': 'A small fiery particle thrown off from a fire, alight in ashes, or produced by striking.',
    'dope': 'A drug taken illegally for recreational purposes.',
    'phrase': 'A small group of words standing together as a conceptual unit.',
    'welsh': 'Relating to Wales or its people or language.',
    'wall': 'A continuous vertical brick or stone structure that encloses or divides an area.',
    'whine': 'To make a long, high-pitched complaining cry or sound.',
    'fickle': 'Changing frequently, especially as regards one\'s loyalties or affections.',
    'wrong': 'Not correct or true; incorrect.',
    'stamina': 'The ability to sustain prolonged physical or mental effort.',
    'dazed': 'Unable to think or react properly; bewildered.',
    'cramp': 'A painful, involuntary contraction of a muscle or muscles.',
    'filet': 'A boneless piece of meat or fish.',
    'foresee': 'To be aware of beforehand; predict.',
    'seller': 'A person who sells something.',
    'award': 'A prize or other mark of recognition given in honor of an achievement.',
    'mare': 'The female of a horse or other equine animal.',
    'uncover': 'To remove a cover or covering from.',
    'drowning': 'The process of dying through submersion in and inhalation of water.',
    'ease': 'Absence of difficulty or effort.',
    'buttery': 'Resembling or containing butter.',
    'luxury': 'A state of great comfort or elegance, especially when involving great expense.',
    'bigotry': 'Intolerance toward those who hold different opinions from oneself.',
    'muddy': 'Covered in or full of mud.',
    'photon': 'A quantum of light or other electromagnetic radiation.',
    'snow': 'Atmospheric water vapor frozen into ice crystals.',
    'oppress': 'To keep someone in subservience and hardship, especially by the unjust exercise of authority.',
    'blessed': 'Made holy; consecrated.',
    'call': 'To cry out to someone in order to summon them or attract their attention.',
    'stain': 'A colored patch or dirty mark that is difficult to remove.',
    'amber': 'A hard, translucent, yellowish-brown fossil resin.',
    'rental': 'An amount paid or received.',
    'ocean': 'A large body of salt water.',
    'galaxy': 'A massive system of stars, dust, and gas held together by gravity.',
    'puzzle': 'A game or problem designed to test ingenuity or knowledge.',
    'mystery': 'Something that is difficult or impossible to understand or explain.',
    'treasure': 'A collection of valuable things hidden or stored in a safe place.',
    'whisper': 'To speak very softly using one\'s breath.',
    'horizon': 'The line at which the earth\'s surface and the sky appear to meet.',
    'dragon': 'A mythical creature typically depicted as a large, fire-breathing reptile.',
    'shadow': 'A dark area or shape produced by an object blocking light.',
    'harmony': 'The combination of different musical notes played or sung simultaneously.',
}